### ISSUE TITLE
Warning about use of dpi in main.css

### ISSUE THREAD

**Issue by adeelejaz** [h5bp/html5-boilerplate#1474]
The following bit in the main.css throws up a warning in Chrome.
https://github.com/h5bp/html5-boilerplate/blob/master/css/main.css#L217
```css
@media print,
       (-o-min-device-pixel-ratio: 5/4),
       (-webkit-min-device-pixel-ratio: 1.25),
       (min-resolution: 120dpi) {
    /* Style adjustments for high resolution devices */
}
```

Warning:
>Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: print, not all, (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi) 

A bit of researching as shows that dppx support is a bit lacking...
- Chrome: 29.0
- Firefox: 16.0
- IE: No Idea
- Opera: 12.10
- Safari: No Idea

Source: https://developer.mozilla.org/en-US/docs/Web/CSS/resolution#Browser_compatibility

I'll try to do some tests today and update if I find anything about support if Safari.

**Comment by fronteed** [comment]
This media expression is used on http://apple.com:

```
@media print,
  only screen and (-webkit-min-device-pixel-ratio: 1.5),
  screen and (min-resolution: 144dpi),
  screen and (min-resolution: 144dppx) {
  // styles
}
```

It's likely a right choice.

1. I don't think that we need to use "-o-min-device-pixel-ratio", since its related to Presto engine, while all the modern versions of Opera browser are based on Webkit engine. Older versions of Opera Mini is the only browser that use Presto engine (server-side rendering). 
2. Styles used by Apple are related to >=1.5 dpr. We likely don't need to load a large sized graphics (the main retina styles purpose) for the screens whose dpr <=1.5.
3. The following styles don't throw a warning in Chrome's console.

**Comment by alrra** [comment]
ping @drublic.

**Comment by drublic** [comment]
Based on our findings and current situation in browsers here is my suggestion:


I don't think we need `-o-min-device-pixel-ratio` anymore.

> since its related to Presto engine, while all the modern versions of Opera browser are based on Webkit engine.

Right, @fronteed.


So the new media query would be:

```
@media print,
       (-webkit-min-device-pixel-ratio: 1.25),
       (min-resolution: 1.25dppx),
       (min-resolution: 120dpi) {
}
```

This is basically what Apple uses, @fronteed.

----

This does not fix false-positives on Windows which result from a problem with Windows' hi-resolution mode. I don't think this is a problem we can handle which is why I would opt for not caring to much about it at the moment.
We should revisit this when something new comes up in the area of Windows hi-res mode.

Any more input on this issue? Are you happy with this solution?

**Comment by alrra** [comment]
> I don't think we need `-o-min-device-pixel-ratio` anymore.

@drublic `-o-min-device-pixel-ratio` has already been removed (see: https://github.com/h5bp/html5-boilerplate/pull/1682#discussion_r26377139, and https://github.com/h5bp/html5-boilerplate/commit/c7057bef0c432c245d678d5ea4cf16526619cafb + https://github.com/h5bp/html5-boilerplate/commit/9581cf3a81ea396e73360ac3a99b8d453f9358e7).

**Comment by drublic** [comment]
> -o-min-device-pixel-ratio has been already removed (see: #1682 (comment), and c7057be + 9581cf3).

Yup, saw that. Just wanted to make sure to take off where we were when the discussion ended last year :)

**Comment by alrra** [comment]
Thank you all for helping us test this!
