### ISSUE TITLE
Drop IE8 support

### ISSUE THREAD

**Issue by alrra** [h5bp/html5-boilerplate#1524]
Microsoft is [ending the extended support](http://www.microsoft.com/en-us/windows/enterprise/end-of-support.aspx) for [Windows XP](http://en.wikipedia.org/wiki/Windows_XP#Support_lifecycle) on April 8, 2014. Since IE8 is mostly a Windows XP browser, and it's market share is slowly but steadily going down¹ , I think we should __start the discussion__ on dropping IE8 support.

--

¹  Some current estimates (feel free to share your own/other):
* [6.15% - StatCounter (March 2014)](http://gs.statcounter.com/#browser_version-ww-monthly-201403-201403-bar)
* [4.24% - W3Counter (February 2014)](http://www.w3counter.com/globalstats.php)
* [5.29% - Clicky (most recent)](http://clicky.com/marketshare/global/web-browsers/internet-explorer/)
* [6.93% - 8.73% - Wikipedia (as of September 2013)](http://en.wikipedia.org/wiki/Internet_Explorer_8)

--

Changes involved with dropping IE8 support:

* Remove IE8 related code
* Switch to jQuery `2.x.x`
* Update conditional comments for _"browse happy"_ prompt
* Remove html5shiv?
* Update documentation
* Other (which?)

**Comment by robinio1** [comment]
I got a problem with this site http://www.fensternachmass-shop.de and IE, it won´t show the pictures.

**Comment by davidjbradshaw** [comment]
Update as of June 1st.

* W3Counter: No longer listed in top 10 
* Clicky: 1.99%
* Statcounter: 1.95%
* Wikipedia: 1.55% (March)

**Comment by arthurvr** [comment]
Wow. It's going in the good direction :)

**Comment by Marsinator** [comment]
I don't know how I became a part of this conversation, you guys probably
have the wrong mail address.

Frank

Am Sonntag, 7. Juni 2015 schrieb Arthur Verschaeve :

**Comment by alex** [comment]
(Not sure how I got CC'd on this issue, but since I'm here anywhere :-)). If you feel like looking at another source for browser usage, there's https://analytics.usa.gov/: sadly IE8 is still at 2.6%.

**Comment by patrickkettner** [comment]
@Marsinator you commented on it back in December - https://github.com/h5bp/html5-boilerplate/issues/1524#issuecomment-67084713

@alex you were @ mentioned by julienetie back in December as well 

y'all can unsubscribe at any time by clicking the unsubscribe button on the right of the issue page

**Comment by ArmorDarks** [comment]
Please, consider that in other regions situation might be very different. For example, sadly enough, in eastern Europe and ru region IE8 still more alive than ever (in most cases, used by corporate sector).

**Comment by jpdevries** [comment]
Hopefully Win 10 and Edge get people to update!



—

**Comment by ArmorDarks** [comment]
I wish companies would appreciate that, but they won't, since win10 will require subscription after free 1 year, and they already bought WinXp, so they don't want to pay for anything else.

So, in case you're working in corporate sector, you're stuck with IE8.

**Comment by jpdevries** [comment]
It's too bad Microsoft flip flopped on their "win 10 will be free even for pirates" announcement. That seemed like the nail in the coffin. 



—

**Comment by stevemao** [comment]
:+1:

**Comment by benfurfie** [comment]
As others have explained earlier on, corporate adoption of newer operating systems and browsers has little to do with the cost and more to do compatibility and change management. The reality is that updating a browser within a corporate environment isn't as simple as updating 1,000+ machines. They need to test every plugin, piece of custom software and service that is used on a daily basis. If the new browser fails on any one of those tests, it isn't implemented.

Forcing these companies to upgrade isn't even as simple as EOL'ing the version of Windows they are using. I have a client who is runs an IT support company. He has two clients who are still running at least one DOS computer because the software they rely on to run their business was never updated.

The cost of moving from that system to another isn't worth the cost, both in terms of financial outlay and lost productivity/sales.

I'm not saying I don't agree with dropping support for IE8. I actually charge my clients double if they want IE8 support. And I also recognise that we're part of the problem – while we keep developing websites that are compatible with IE8, we keep allowing them to continue to use IE8.

However, the reality is that we're just one small piece of the puzzle. As for Microsoft making Windows 10 a subscriptions service? That doesn't even factor into the equation.

**Comment by clarkdemvher** [comment]
On Jun 16, 2015 1:56 PM, "Ben Furfie" <notifications@github.com> wrote:
>
> As others have explained earlier on, corporate adoption of newer
operating systems and browsers has little to do with the cost and more to
do compatibility and change management. The reality is that updating a
browser within a corporate environment isn't as simple as updating 1,000+
machines. They need to test every plugin, piece of custom software and
service that is used on a daily basis. If the new browser fails on any one
of those tests, it isn't implemented.
>
> Forcing these companies to upgrade isn't even as simple as EOL'ing the
version of Windows they are using. I have a client who is runs an IT
support company. He has two clients who are still running at least one DOS
computer because the software they rely on to run their business was never
updated.
>
> The cost of moving from that system to another isn't worth the cost, both
in terms of financial outlay and lost productivity/sales.
>
> I'm not saying I don't agree with dropping support for IE8. I actually
charge my clients double if they want IE8 support. And I also recognise
that we're part of the problem – while we keep developing websites that are
compatible with IE8, we keep allowing them to continue to use IE8.
>
> However, the reality is that we're just one small piece of the puzzle. As
for Microsoft making Windows 10 a subscriptions service? That doesn't even
factor into the equation.

**Comment by jdalton** [comment]
:+1: for dropping support for future releases. Devs wanting IE8 support can always use an older version.

**Comment by jdalton** [comment]
jQuery, Lodash, and [possibly others](https://github.com/jashkenas/backbone/issues/3828) are planning to drop IE8 support as part of their next major version bumps.

**Comment by QWp6t** [comment]
| sauce                                                                                            | marketshare | methodology publicly available?                                                     | notes                                                                                             |
|--------------------------------------------------------------------------------------------------|-------------|-------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| [clicky.com](https://clicky.com/marketshare/global/web-browsers/internet-explorer/)              | **0.3%**    | nah                                                                                 |                                                                                                   |
| [w3counter.com](https://www.w3counter.com/trends)                                                | **0.5%**    | nah                                                                                 |                                                                                                   |
| [analytics.usa.gov](https://analytics.usa.gov/)                                                  | **0.4%**    | [maybe?](https://www.digitalgov.gov/services/dap/)                                  | [raw data is available](https://analytics.usa.gov/data/)                                          |
| [wikimedia.org](https://analytics.wikimedia.org/dashboards/browsers/)                            | **0.67%**   | unknown                                                                             | uses piwik to gether data                                                                         |
| [statcounter.com](http://gs.statcounter.com/#browser_version-ww-monthly-201607-201607-bar)       | **0.97%**   | [yep](http://gs.statcounter.com/faq#methodology)                                    |                                                                                                   |
| [net marketshare](http://marketshare.hitslink.com/browser-market-share.aspx?qprid=2&qpcustomd=0) | **4.79%**   | [yep](http://www.netmarketshare.com/faq.aspx)                                       | [weights data by country](http://www.netmarketshare.com/faq.aspx#Country), counts unique visitors instead of pageviews |

**Comment by roblarsen** [comment]
Not surprisingly, nine months later, things have clarified.

**Comment by roblarsen** [comment]
So, I opened a PR #1892  
Two things

- Is the PR missing anything (other than a shiv-less Modernizr, which I'll add shortly)? 
- Should we remove the browsehappy block (the PR as it stands) or pull in the new version from #1748 Thinking about it, I think pulling in #1748 is a good idea, but I could be convinced otherwise (since my original inclination was to do away with it altogether.)

**Comment by JohnnyWalkerDesign** [comment]
Personally I'd feel more comfortable keeping BrowseHappy in. It has zero overhead and covers for any old IE users you may encounter. But maybe IE8/9 have so small a marketshare it's not worth it?

**Comment by marinintim** [comment]
@roblarsen: README still says that H5BP is IE8+

**Comment by JohnnyWalkerDesign** [comment]
@roblarsen It also still says `lt 8` instead of `lt 9`.

**Comment by roblarsen** [comment]
@marinintim Thanks for the heads up

**Comment by roblarsen** [comment]
@JohnnyWalkerDesign That's coming in as a separate PR.
