### ISSUE TITLE
Move Modernizr to the bottom

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5-boilerplate#1605]
It has more potential to introduce unexpected situations, however it's much better for the user to just have no scripts up in the head at all.
## [Guide to Using Modernizr responsibly.](https://github.com/Modernizr/Modernizr/issues/878#issuecomment-41448059)

I bet >75% of sites dont need it in the head. I'd rather change this default and educate the 25% than watch as we slow down all these sites.

**Comment by arthurvr** [comment]
@drublic Do you already have (some?) results?

**Comment by drublic** [comment]
We don't have a lot of numbers from our production websites yet but here are some test numbers:

We now load html5shiv in `header.min.js` and our Modernizr custom build in `core.js`. Before the change, Modernizr was loaded in `header.min.js` too.

The change saves us in `header.min.js`
gzipped 3.4KB (2.7 KB compared with 6.1 KB before)
unzipped 10KB (5.6 KB compared with 15.6 KB before)

The saved data moves to `core.js`
gzipped 2.6 KB (82.4 KB compared with 79.8 KB)
unzipped 7 KB (258 KB compared with 251 KB)

This means we save bytes (because of how gzip works) and deliver the first view faster.
We did not encounter any problems with rendering within our project.

**Comment by roblarsen** [comment]
ayo, I merged in code that does this 💯
