### ISSUE TITLE
Favicon test from realfavicongenerator.net

### ISSUE THREAD

**Issue by ahite-archermalmo** [h5bp/html5-boilerplate#1670]
Is this an issue of concern?
http://realfavicongenerator.net/favicon_checker?site=http%3A%2F%2Fhtml5boilerplate.com%2F&ignore_root_issues=on#.VNp8ZcY0XP4

**Comment by alrra** [comment]
@ahite-archermalmo Please open future issues regarding https://html5boilerplate.com/ in the https://github.com/h5bp/html5boilerplate.com repository. Thanks!.

--

As for some of the issues:

> iOS Favicon
>
> Some iOS pictures are not declared
> 
    114x114 picture
    72x72 picture
    144x144 picture
    60x60 picture
    120x120 picture
    76x76 picture
    152x152 picture
    180x180 picture


You don't need to have all of them, see: https://github.com/h5bp/html5-boilerplate/issues/1367.

> iOS Favicon
>
> Some iOS pictures are not declared:
> ...
>    `180x180 picture`

A `180x180` picture is defined, see: https://html5boilerplate.com/apple-touch-icon.png. 

> Bakground color for Windows 8 tile is not defined. Windows will choose it for you, which is probably not what you want.

We don't use a tile image that has transparent parts, so specifying the `color` doesn't do anything for our particular case (see also: https://github.com/h5bp/html5-boilerplate/pull/1481).

As for some of the other issues, we do not include those icons due to the low usage in regard to out particular site. 

--

We should however include a [web application manifest file](https://github.com/h5bp/html5-boilerplate/pull/1629).

**Comment by ArmorDarks** [comment]
Btw, worth to review report once again, since it is different now.
