### ISSUE TITLE
.visuallyhidden class causes problems when used on form fields

### ISSUE THREAD

**Issue by gadgetto** [h5bp/html5-boilerplate#1687]
Using .visuallyhidden causes strange problems when used on form fields.
In my case I used the class on a form field which I placed to provide a honeypot for spambots.

The result was a page layout problem that generated horizontal scrollbars and stretched the width of the layout.

Here is a CodePen sample which demonstrates the problem:
http://codepen.io/anon/pen/QwzaWp

**Comment by TheDutchCoder** [comment]
It's because you've made your field 100% width, but didn't position their parents.
This means the form field will take up the whole page width (and cause overflow on the document).

Simply set your wrapping paragraphs to have a `position: relative;` and you should be good.
This is not so much a bug in HTML5BP as it's your own styling that causes this ;-)

**Comment by alrra** [comment]
@TheDutchCoder Thanks for looking into it!

**Comment by gadgetto** [comment]
Thanks for clarification!

**Comment by TheDutchCoder** [comment]
Glad to help!
