### ISSUE TITLE
Why don't you use an array of favicons?

### ISSUE THREAD

**Issue by SNUPww** [h5bp/html5-boilerplate#1695]
The ico format gives you the opportunity to have more then 1 favicon (one for low-res screens, one for higher). Why don't you use it?

**Comment by alrra** [comment]
> The ico format gives you the opportunity to have more then 1 favicon (one for low-res screens, one for higher). Why don't you use it?

@SNUPww Browsers will automatically resize the `favicon`, so there isn't really a need to include multiple images. We include only one `32x32px` image mainly because we want to keep the size as small as possible by default.

However, if you use art-direction and want to have different content for each size then, by all means, include multiple images (just don't forget to configure your [server](https://github.com/h5bp/server-configs) to serve the `favicon.ico` compress and with far-future expires headers).

**Comment by arthurvr** [comment]
@alrra Something for the docs maybe?

**Comment by alrra** [comment]
> Something for the docs maybe?

@arthurvr Improvements to the docs are always welcomed, so feel free to open a pull request! :)
