### ISSUE TITLE
stylesheet caching control

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1723]
I'm told the main stylesheet caches for up to a year. I had been wondering why some of my tweaks to my styles in main.css had no effect until maybe weeks later. If something in normalize.css or main.css is causing this caching, please clarify the comments in the *.css so we can adapt the settings. Solutions to caching are discussed at <http://andrewapeterson.com/2011/02/ipage-css-changes-not-taking-effect-due-to-cache-youre-not-crazy-and-its-not-your-fualt?track=facebucketchallenge>, <https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching>, <http://blog.marek.sapota.org/article/2012/08/17/web-browsers-and-cache-revalidation.html>, <http://stackoverflow.com/questions/460389/browser-caching-of-css-files>, <http://stackoverflow.com/questions/12992717/how-to-prevent-css-caching-on-a-web-page>, <https://css-tricks.com/can-we-prevent-css-caching/>, <http://www.impressivewebs.com/force-browser-newest-stylesheet/>, and apparently elsewhere, but I don't like having to learn another language, requiring users to have to clear a cache in order to see a website as I intended it, or having to edit a link element in every HTML page (I have a lot of pages) whenever I edit a *.css file. Probably someone knows more about this than I do. I'd like something I can write that forces immediate use of the latest revision of a *.css file, perhaps by not allowing caching or keeping it to within a short duration I specify until I eventually stabilize CSS and can support longer durations. I'd rather set the duration in one place, not separately in every HTML file (I don't use PHP).

**Comment by lucaspetter** [comment]
@Nick-Levinson

The issues you're having are caused by HTML5 Boilerplate's default cache settings in the [.htaccess](https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess) file.

You'll need to edit your `.htaccess` file (it's a hidden file, so make sure you can see hidden files). Scroll to the section titled "Web Performace," then to the sub-section "Expires Headers." Here, you can control the expiry/cache times for various file types.

By default, CSS has this setting:
```
# CSS

ExpiresByType text/css                              "access plus 1 year"
```
This means your server will send an `Expires` header with a date 1 year from the time of access for all CSS files. Browsers will cache these files for up to 1 year and may not bother downloading them again until this time has passed. The caching is happening in visitors' browsers, not on your server.

Using the `Expires` header is like making a commitment to browsers that a file won't change for X amount of time, so browsers are safe to cache it and don't need to re-download it again and again. It's great for speeding up page load times and lightening the burden on your server.

If you need to frequently change a file, you should make sure it has a short or immediate expiry time. In your case, you might want to change the setting to something like `"access plus 1 day"`, or `"access plus 0 seconds"` to expire files immediately so browsers won't cache them at all.

*Even if you do shorten the expiry time in `.htaccess`*, browsers that have previously cached an old version of a file may still remember the 1 year expiry time and not bother downloading the newer version of that file. To fix this, if you rename the file and all references to it in your HTML, browsers will be forced to download it [1].

In your case, you'd have to update all the `<link>` elements in all your pages to use the new CSS filename. However, you may only need to do this once now that you know how `Expires` headers work and you've set a short or immediate expiry time in `.htaccess`. Also, some text editors have a multi-file find-and-replace feature to make this easier [2]. To find more ways of editing multiple files, try looking up "multi file find and replace" in a search engine.

---

[1]  There are [advanced ways](http://heatherevens.me.uk/2013/07/01/filename-based-cache-busting-made-easy/) of automatically controlling file version caching by renaming the files - you can look into "filename-based cache busting" for more info.
[2] [TextWrangler](http://www.barebones.com/products/textwrangler/) (for Mac) has a "Multi-File Search" menu option.

**Comment by Nick-Levinson** [comment]
Okay, I get it. I'll assume the .htaccess method will work and I'll close this issue now. Thanks.
