### ISSUE TITLE
forcing vertical scrollbar

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1725]
Here and there, a page bottom doesn't display and no vertical scroll bar is present, and this is specific to a small percentage of websites, because scroll bars appear on other sites in the same browser session. I use Firefox, so this isn't affected by the textarea rule in normalize.css for IE. Narrowing the Firefox viewport made the bottom available. (I can't cite an example because the one I recently saw (where the bottom of the proprietor's signature was chopped off until the viewport was narrowed) was repaired and archive.org and Google's cache don't have it.) I tried asking why it might not appear and didn't find out but was advised on how my pages could support a scroll bar if needed (<http://www.webdesignforums.net/forum/general-web-design-discussion/44731-scrollbar-missing-certain-pages.html#post273059>, as accessed July 17, 2015), but I'm not sure if this step is needed or is correct, haven't tested it, and would rather see if you'd want to include it (I'm providing it verbatim from the linked-to answer, except for some whitespace and including the comment that I assume is disposable):
html {
overflow: scroll;
/* active y scrollbar, delete if you not need it */
height: 101%;
}

**Comment by danellebailey** [comment]
Hi Nick, 

Can you provide some active examples?

**Comment by Nick-Levinson** [comment]
I wish I could, but no. I see one or another on occasion, but I don't have a list and no regularly-visited site comes to mind. The last one I saw was set up by a firm that offers to set up sites for many small businesses and it seemed to use scripts a lot, Maybe a script suppressed the vertical scrollbar until I pointed out the lack and the small business fixed it. We shouldn't countermand scripts even if their effect is unintentional, but if it's not a scripted effect then maybe we should force a scrollbar if somehow it fails to appear on its own with too-long content.

**Comment by WebNinjrDesign** [comment]
I'd say this is probably (as you said) specific to a small percentage of websites, and thus think it's probably really something to do with their coding or some random plugin. I'd say its not something that would really go into H5BP unless its a common enough issue and would be required across the board, and not related to code used after H5BP is in place.

Saying that, I have seen what you've mentioned once or twice a while ago. I simply assumed they had written their website poorly and that was causing the issue.

Personally I don't think we should set a standard to show the scroll bar unless it's needed, but there has been a lot of talk about this so that pages don't jump left to right on a single site going between pages that do and don't have scroll bars. I figure this is something site specific, and thus should just be snippet to insert when needed.

**Comment by danellebailey** [comment]
I agree. This seems to be an edge case.

**Comment by alrra** [comment]
> forcing vertical scrollbar 

Closing as this isn't something HTML5 Boilerplate should do.
