### ISSUE TITLE
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->

### ISSUE THREAD

**Issue by fghhfg** [h5bp/html5-boilerplate#1736]
This is [ie conditional comments](https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx):

```
<!--[if expression]> HTML <![endif]-->
```

then why are you add `<!-->` and `<!--` inside (`<!--[if gt IE 8]>` and `<![endif]-->`)?

Is it necessary?

some program complain that it is unclosed comment...

**Comment by QWp6t** [comment]
H5BP doesn't contain the code you're talking about. The only IE conditional comment is an [alert advising users to upgrade their browser](https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html#L18-L20).

But to answer your questions...

> then why are you add `<!-->` and `<!--` inside (`<!--[if gt IE 8]>` and `<![endif]-->`)?

It's to prevent the code from being read by non-IE browsers. We only want IE to read what's within the condtiional statement.

> Is it necessary?

Yes, otherwise all browsers would show that alert. Or, in your case, all browsers would be seeing two `html` tags, which is clearly bad markup.

> some program complain that it is unclosed comment...

That program is wrong.

**Comment by fghhfg** [comment]
> H5BP doesn't contain the code you're talking about.

You are right.

```html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
...
```

this part come from [initializr](http://www.initializr.com/) in [here](http://www.initializr.com/builder?print&izr-responsive&jquerymin&h5bp-iecond&h5bp-chromeframe&h5bp-analytics&h5bp-favicon&h5bp-appletouchicons&modernizrrespond&h5bp-css&h5bp-csshelpers&h5bp-mediaqueryprint&izr-emptyscript)

**Comment by olcanarslan92-dot** [comment]
#3264
