### ISSUE TITLE
CSP URL outdated

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1771]
In .htaccess > Security > Content Security Policy (CSP), you should update the URL http://www.w3.org/TR/CSP11/ to http://www.w3.org/TR/CSP2/ (going from Level 1 to Level 2, a Candidate Recommendation, to which the old URL is redirecting anyway) and perhaps add the URL for the Level 3 Editor's Draft, <http://w3c.github.io/webappsec-csp/>.

Links to whatever is the latest version include http://www.w3.org/TR/CSP2/ and <http://www.w3.org/TR/CSP/>.

If there's any interest in linking to Level 1 anymore, the likely link would be to http://www.w3.org/TR/2012/CR-CSP-20121115/ (CSP 1.0, Candidate Recommendation) or http://www.w3.org/TR/2014/WD-CSP11-20140211/ (CSP 1.1, Working Draft).

The URLs here were as accessed Dec. 25, 2015.

**Comment by alrra** [comment]
@Nick-Levinson Fixed in https://github.com/h5bp/server-configs-apache/commit/c23b8a1aea30ddaaa5627ae6a9d7d5d5b0ff5478. Thanks!

--

In the future, please [open issues](https://github.com/h5bp/html5-boilerplate/blob/5e0b0d642b6d5f633714a2929a5a35d26330bfd3/CONTRIBUTING.md#using-the-issue-tracker) related to the `.htaccess` file in the [Apache Server Configs](https://github.com/h5bp/server-configs-apache) repository.
