### ISSUE TITLE
"should be send" should be corrected

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1773]
This looks like a typo but I don't know what's intended, and that's a more likely problem. In .htaccess > Internet Explorer > Document Modes, "should be send" should be edited but I do not know whether to "should be sent" or to "should be set".

**Comment by alrra** [comment]
@Nick-Levinson Fixed in https://github.com/h5bp/server-configs-apache/commit/aa74927eb233d53b1b23813af5135c9c3613385b. Thanks!

--

In the future, please [open issues](https://github.com/h5bp/html5-boilerplate/blob/5e0b0d642b6d5f633714a2929a5a35d26330bfd3/CONTRIBUTING.md#using-the-issue-tracker) related to the `.htaccess` file in the [Apache Server Configs](https://github.com/h5bp/server-configs-apache) repository.

**Comment by vlakoff** [comment]
Actually it had been fixed in https://github.com/h5bp/server-configs-apache/commit/f71aa7a6508a4842d02c28749f30d012a6b7b63e already, and you *reintroduced* the typo in https://github.com/h5bp/server-configs-apache/commit/aa74927eb233d53b1b23813af5135c9c3613385b :p
