### ISSUE TITLE
Add Open Graph metadata

### ISSUE THREAD

**Issue by thecodeboy** [h5bp/html5-boilerplate#1911]
### Why do this?

The [Open Graph protocol](http://ogp.me/) optimizes your content for social sharing and rich story previews. This improves website distribution through social news feeds.

**A small endeavour to improve page discovery.** :zap: 

May I send a pull request? :man:

**Comment by quantumpacket** [comment]
@thecodeboy I'd check out the previous times this has been [brought up](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=open%20graph%20). The consensus has usually been to just improve the [documentation](https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/extend.md#social-networks) rather than add it to the markup.
