### ISSUE TITLE
RFC: Migrate to npm scripts

### ISSUE THREAD

**Issue by amilajack** [h5bp/html5-boilerplate#1927]
Throwing out gulp from the stack means removes some of the fatigue from developing with js. Would be nice if we could depend solely on npm scripts, which are much more natural to developers. [js-stack-from-scratch](http://github.com/verekia/js-stack-from-scratch) has done this migration and I think this repo should as well. **Willing to make the PR for this.**

Thoughts?

**Comment by roblarsen** [comment]
Can you elaborate on the "fatigue" and how npm scripts are "more natural to developers?"

I'm not really interested in this, but if you want to make the case I'd be interested in your reasoning behind those statements.

**Comment by amilajack** [comment]
[This is a nice read from a while ago](https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.xteohpsm2) that explains why one should favor npm scripts over gulp.

Here's a quite common example. Lets say you want to add eslint support with gulp. That means that you need to install gulp-eslint instead if eslint itself. Using gulp-* plugin means that you need to know how it works. If you're a grunt developer, you have to learn how grunt works and vice versa. Can actually be used out of the box without any other plugins or test runners.

```
npm i -D eslint
```
```js
{
  "scripts": {
    "lint": "eslint ."
  }
}
```
**Done**

Simplicity is key for javascript boilerplates, since many are used by people that use them don't have much experience with javascript. If we can afford to remove unnecessary tools, we should. One of the biggest criticisms that the JS community gets is that its has so much tooling that its hard for beginners to get started.

**Comment by roblarsen** [comment]
Thanks for that. I'll keep this open as it's an appealing idea with some merit (and I quite like npm scripts.) but gulp works so I'm going to table this idea for the time being. 

Some explanation follows:

> One of the biggest criticisms that the JS community gets is that its has so much tooling that its hard for beginners to get started.

I'm the king of that criticism e.g., [once](https://twitter.com/roblarsenwww/status/842044333259919361) and  [twice](https://twitter.com/roblarsenwww/status/841374319657799685) in the past three weeks. 

But I'm also a king of criticizing the JS community for focusing way too much on plumbing* and not focusing on users. 

In the case of H5BP our users (in our case, both the developer and _their_ end-users) aren't actually going to use gulp or grunt or npm or eslint or anything. We're using those tools as maintainers and contributors to ensure that we're doing a good job of developing the project- a static, standalone directory of files that represents the best starting point for modern development we can offer.  To my mind, if something works (gulp,and, _tbh_, jshint) and switching doesn't actually change the output for our users, then I automatically start off skeptical about the value of the change. 

For a concrete example of what I'm talking about. switching from gulp would change the experience of _zero_ people using the web. No web user would ever see anything different. 

On the other hand, compare that to my main goal right now. My main goal is to work on the two Modernizr issues (#1740 #1605) Because most people don't change our defaults those issues will change the experience for millions of web users since that's code that actually ships with the project. 

I only have a limited time to work on this project every week and I've got to pick my spots. Even when there's a PR I need to manage the PR and that takes away time from some of the other things I'd like to do (including, you guessed it, the Modernizr issues.) 

*I know I was doing plumbing way-back-when and I obviously still think it matters. I just don't obsess over it and am skeptical of the need to completely rewrite tooling every six months to stay up-to-date.  I mean, `make` is over 40 years old.

**Comment by janschloss** [comment]
Since gulp isn't included in the distribution files I agree with @roblarsen here that the requested change is unnecessary.

**Comment by roblarsen** [comment]
Closing because of cobwebs.
