### ISSUE TITLE
RFC: Restrict node engine to >= 4

### ISSUE THREAD

**Issue by amilajack** [h5bp/html5-boilerplate#1929]
Node < 4 is deprecated.

Willing to PR for this

**Comment by roblarsen** [comment]
Please PR

**Comment by amilajack** [comment]
Just made the PR for this

**Comment by roblarsen** [comment]
closed via #1931 

Since you're involved in a few conversations right now- with the next PR that's related to an issue, you can reference the issue number directly [with "closes #xxxx"](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message and it will:

- show up in the comments on the issue
- automatically close the issue when it's merged in.

**Comment by roblarsen** [comment]
(and.... thanks!)

**Comment by amilajack** [comment]
> with the next PR that's related to an issue, you can reference the issue number

Thanks. Will make sure to do this next time
