### ISSUE TITLE
Add theme-color meta tag to index.html

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2073]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

Chrome for Android and Samsung Internet supports the `<meta name="theme-color" content="#3c790a">` meta tag.
https://caniuse.com/#feat=meta-theme-color

We cover this briefly in our docs (https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/extend.md#theme-color) but I think the meta tag should now be included in the default `index.html` template. Chrome for Android has a huge browser marketshare (33%) and adding a theme-color is a useful addition for all websites and webapps.

**Comment by roblarsen** [comment]
I like the idea. We need to pick something benign for the default value.

**Comment by roblarsen** [comment]
or... Hot Pink?

**Comment by jonathantneal** [comment]
Hot Pink has been the tradition of H5BP. Wasn’t that the default text selection color once?

**Comment by coliff** [comment]
ha. I think many people may not think to change it though so I think a light gray might be best.

**Comment by jonathantneal** [comment]
Yes... that was also the tradition... to later remove it for exactly that reason... Mmm... memories...

Yea so probably not hot pink 😄

**Comment by coliff** [comment]
The amended web.manifest PR #2060  we have has theme_color as #fafafa - almost white. I suggest we go with that. Is that ok? whatever we choose the theme_color must match in both the web.manifest and the HTML meta tag.

**Comment by coliff** [comment]
This is addressed in #2074

**Comment by Richienb** [comment]
As an addition to @coliff, #fafafa is Google's recommendation of background colour in order to convey a nice contrast against pure white cards that have shadows.

Take a look at the following example from the official Material Design website.
The background colour behind the cards is in fact, #fafafa.

[![Background colour example](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1pB6APqAPaoNv8E8de2yZ4W6xiWCb8hn-%2Fcolor-applyingcolorui-typography-baseline-alt.png)](https://material.io/design/color/applying-color-to-ui.html#typography-iconography)

**Comment by coliff** [comment]
Added in #2074.

**Comment by Richienb** [comment]
Finally!
