### ISSUE TITLE
Including google analytics without GDPR info

### ISSUE THREAD

**Issue by maciekpaprocki** [h5bp/html5-boilerplate#2242]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

I noticed that html5 boilerplate is still including google analytics by default. Personally I wouldn't really try to promote it here as it's not really considered a good set of practice ( although often required ). However, in GDPR times using it without information can actually get you in troubles. 

Possible solutions:
- remove analytics code
- comment analytics code
- annotate it with info about GDPR
- comment analytics code and annotate it with info about GDPR

Happy to send PR if you have recommended way to go.

**Comment by roblarsen** [comment]
We've discussed it previously and my mind hasn't really changed about including GA. As for your suggestions to improve this, we're not going to ship commented out code and/or inline documentation. If you want to propose some further documentation to explain the issues around GDPR then I'd be happy to see that.

**Comment by maciekpaprocki** [comment]
Personally, I didn't check documentation in years ( not that much in HTML is changing ), however, I often use repo. 

There are other inline comments like `<!-- Place favicon.ico in the root directory -->` including even one about analytics. Wouldn't be smart to also add that including it without user confirmation is a big no-no?

**Comment by roblarsen** [comment]
We keep the documentation up to date since the project touches on many subjects. The documentation is the place for discussion of GDPR. There is no way we can explain GDPR in a ten word sentence. 

There are three comments in the HTML. One is legacy (the favicon.ico comment, which is probably a candidate for removal) and then a comment about where to put your site and then the single instruction "Google Analytics: change UA-XXXXX-Y to be your site's ID," which itself is also a candidate for removal. We used to have much more complicated documentation inline, in the source code and have since moved away from that. I'm not interested in starting that back up again. We **can and do** educate, we just don't do it in the source code.

**Comment by maciekpaprocki** [comment]
Yeah, I meant more to include a link to somewhere. Definitely not a thing for a one-liner. 

OK. That explanation makes sense. I've read through the old stuff about analytics and although I don't agree I understand why you keep that.

**Comment by isaac-friedman** [comment]
I'm looking for ways to be useful to the community. Can I take this issue and put a paragraph or two about Google Analytics and GDPR in the documentation?

**Comment by roblarsen** [comment]
@isaac-friedman  Yes 👍

**Comment by roblarsen** [comment]
closed with #2262
