### ISSUE TITLE
Fix failing dependabot initiated "push to template repo" builds

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2711]
[chore\(deps\-dev\): update webpack requirement in /src \(\#2710\) · h5bp/html5\-boilerplate@e64c4a5](https://github.com/h5bp/html5-boilerplate/actions/runs/1876062624)

🤔

**Comment by coliff** [comment]
heya - this issue title is 'Fix failing **dependabot**...' do you mean GitHub Actions? I had a look and didn't see any dependabot related issue there.

I had a quick look at the code and only thing I can think of it is that the Personal Access Tokens might not be set right? Maybe regenerate it and try again? We've used the GitHub Actions versions since February so hopefully it might work now.

**Comment by roblarsen** [comment]
I can write it up in more detail, but it ONLY fails with dependabot initiated builds. When I merge regular PRs it works
