### ISSUE TITLE
Arial and Helvetica vs just sans-serif

### ISSUE THREAD

**Issue by Garowetz** [h5bp/html5-boilerplate#42]
From Comment on html5boilerplate.com: http://html5boilerplate.com/#comment-67622441

Key Points:

> In general Arial is a better _screen_ font than Helvetica being developed for the screen in the first place. More pressing problem is that Helvetica on Windows does not render well at all and you don't want to ignore the majority of your audience ;) - http://html5boilerplate.com/#comment-67626905
> 
> This is very true - Helvetica on Windows looks awful. But can't this be solved by simply using sans-serif as the first font-face? I'm pretty sure that will default to Helvetica on Macs and Arial on Windows. - http://html5boilerplate.com/#comment-67654932

**Comment by tomasz1986** [comment]
This is a very old issue but `sans-serif`, at least in Windows, is language/locale dependent. The default sans-serif fonts in certain language versions of the OS (e.g. Chinese, Japanese and Korean) are very different from Helvetica or Arial. If your `font-family` is set to `sans-serif` then those systems will display it using their default sans-serif fonts. This happens regardless of the language used on the site, and causes issues with other languages that use special characters not included in those default sans-serif fonts.

**Comment by roblarsen** [comment]
@tomasz1986 It is an old issue, but discussion is always welcome. In this case, the `font-family: sans-serif` definition is now defined in the dependency [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css#L14)

**Comment by tomasz1986** [comment]
> In this case, the font-family: sans-serif definition is now defined in the dependency normalize.css

Yes, I am aware of that :)

I am just trying to say that `font-family: sans-serif` may lead to broken / inconsistent fonts when used on multilanguage / international sites. For example, if I view a Polish website using a Korean version of Windows, and the site uses just `font-family: sans-serif` then the Polish characters will come up broken, because the default sans-serif font in a Korean system is "Malgun Gothic" which looks very different from Western fonts like Arial or Helvetica and also does not include any other language specific characters.
